services:
    nginx:
        image: nginx:latest
        ports:
            - 127.0.0.1:80:80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - backend
            - frontend

    backend:
        build: ./api
        command:
            ["python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "app.py"]
        ports:
            - 127.0.0.1:5678:5678
        volumes:
            - ./api:/app

    frontend:
        image: node:23
        working_dir: /app
        command: ["npm", "run", "dev", "--", "--host"]
        ports:
            - 127.0.0.1:5174:5174
        volumes:
            - ./react:/app
        depends_on:
            - backend
